name: Build Godot Project

on:
  push: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: web
          preset: web
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - web
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/${{ steps.build.outputs.build }}